name: MadeByMe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  intl: ^0.17.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.0.7
  firebase_database: ^10.0.7
  image_picker: ^0.8.6
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - lib/assets/config/vision_service_account.json
